services:
  api:
    build:
      context: ./src/api
      dockerfile: ./Memoraid.WebApi/Dockerfile
    container_name: api
    ports:
      - "5247:8080"
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=database;Port=5432;Username=postgres;Password=P@ssword1;Database=memoraid"

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_PASSWORD: P@ssword1
    ports:
      - "5432:5432"
      
  migrations:
    build:
      context: ./src/database/migrations
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssword1
      POSTGRES_DB: memoraid
      
  test-data-seed:
    build:
      context: ./src/database/test-data-seed
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssword1
      POSTGRES_DB: memoraid