name: Deploy

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  MIGRATIONS_IMAGE_NAME: ${{ github.repository }}/migrations

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run database migrations with Docker
        run: |
          echo "Running database migrations..."
          docker pull ${{ env.REGISTRY }}/${{ env.MIGRATIONS_IMAGE_NAME }}:latest
          docker run --rm --network=host \
            -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            ${{ env.REGISTRY }}/${{ env.MIGRATIONS_IMAGE_NAME }}:latest
      
      - name: Deploy API
        run: |
          echo "Deploying API..."
          curl "${{ secrets.RENDER_API_DEPLOY_HOOK_URL }}"
      
      - name: Deploy App
        run: |
          echo "Deploying App..."
          curl "${{ secrets.RENDER_APP_DEPLOY_HOOK_URL }}"