name: Deploy

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  MIGRATIONS_IMAGE_NAME: ${{ github.repository }}/migrations

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run database migrations
        run: |
          echo "Running database migrations..."
          docker pull ${{ env.REGISTRY }}/${{ env.MIGRATIONS_IMAGE_NAME }}:latest
          docker run --rm --network=host \
            -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            ${{ env.REGISTRY }}/${{ env.MIGRATIONS_IMAGE_NAME }}:latest

      - name: Deploy API
        uses: ./.github/actions/deploy-to-render
        with:
          deploy-hook-url: ${{ secrets.RENDER_API_DEPLOY_HOOK_URL }}
          service-id: ${{ secrets.RENDER_API_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Deploy App
        uses: ./.github/actions/deploy-to-render
        with:
          deploy-hook-url: ${{ secrets.RENDER_APP_DEPLOY_HOOK_URL }}
          service-id: ${{ secrets.RENDER_APP_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
