name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: ${{ github.repository }}/api
  APP_IMAGE_NAME: ${{ github.repository }}/app
  MIGRATIONS_IMAGE_NAME: ${{ github.repository }}/migrations

jobs:
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract branch name and sanitize for tag
        id: branch-name
        shell: bash
        run: |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          SANITIZED_BRANCH_NAME=${BRANCH_NAME//\//-}
          echo "branch=$SANITIZED_BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ env.MIGRATIONS_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=,format=short
            latest

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: ./src/api
          dockerfile: ./Memoraid.WebApi/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ steps.branch-name.outputs.branch }}-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push App image
        uses: docker/build-push-action@v6
        with:
          context: ./src/app
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:${{ steps.branch-name.outputs.branch }}-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
            VITE_FIREBASE_PROJECT_ID=${{ vars.VITE_FIREBASE_PROJECT_ID }}
            VITE_FIREBASE_API_KEY=${{ vars.VITE_FIREBASE_API_KEY }}
            VITE_FIREBASE_AUTH_DOMAIN=${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}
            VITE_FIREBASE_STORAGE_BUCKET=${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}
            VITE_FIREBASE_MESSAGING_SENDER_ID=${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID }}
            VITE_FIREBASE_APP_ID=${{ vars.VITE_FIREBASE_APP_ID }}

      - name: Build and push Migrations image
        uses: docker/build-push-action@v6
        with:
          context: ./src/database/migrations
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.MIGRATIONS_IMAGE_NAME }}:${{ steps.branch-name.outputs.branch }}-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.MIGRATIONS_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
